// Generated by CodiumAI
import { ImSun } from "react-icons/im";
import { App } from "./App";
import { mount, configure, shallow } from 'enzyme'
import Adapter from '@cfaester/enzyme-adapter-react-18';
configure({adapter: new Adapter()});

describe('App', () => {

    // Test that the theme toggles between light and dark when the toggleTheme function is called
    it('should toggle the theme when the toggleTheme function is called', () => {
      const wrapper = mount(<App />);
      const toggleButton = wrapper.find(ImSun);

      // Initial theme should be light
      expect(document.body.className).toBe('light');

      // Click the toggle button to switch to dark theme
      toggleButton.simulate('click');
      expect(document.body.className).toBe('dark');

      // Click the toggle button again to switch back to light theme
      toggleButton.simulate('click');
      expect(document.body.className).toBe('light');
    });

    // Test that the theme toggles between light and dark when the toggleTheme function is called
    it('should toggle the theme when the toggleTheme function is called', () => {
      const wrapper = mount(<App />);
      const toggleButton = wrapper.find(ImSun);

      // Initial theme should be light
      expect(document.body.className).toBe('light');

      // Click the toggle button
      toggleButton.simulate('click');

      // Theme should be dark after clicking the toggle button
      expect(document.body.className).toBe('dark');

      // Click the toggle button again
      toggleButton.simulate('click');

      // Theme should be light again after clicking the toggle button again
      expect(document.body.className).toBe('light');
    });

});
